global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-server'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: 'api-server'

  - job_name: 'ws-server'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          service: 'ws-server'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
